### PR TITLE
support patching weak function

### PR DESCRIPTION
**Pull request by libin2015**

### CODE REVIEW

**Comment by jpoimboe** [comment]
Instead of creating a new lookup_weak_global_symbol() function, how about just adding the WEAK check to lookup_global_symbol()?

**Comment by libin2015** [comment]
Yes, if the two patch is exactly correct, and can be merged together,  we can just adding the WEAK check to lookup_global_symbol.  Thanks.

**Comment by jpoimboe** [comment]
Yes, otherwise it looks right to me, so if you can rebase them into a single commit with the change to lookup_global_symbol, I'll give it a :+1: .  Thanks for the fix!

**Comment by libin2015** [comment]
OK, I will do it and create a new pull request. Thanks.

**Comment by jpoimboe** [comment]
Continued with #508.  (next time, please rebase and force push the existing branch instead of opening a new pull request)

**Pull request closed without merging**
