### PR TITLE
Test cleanups

### PR DESCRIPTION
**Pull request by jpoimboe**
Some cleanups for the unit and integration tests.

### CODE REVIEW

**Comment by jpoimboe** [comment]
Agreed, I was thinking F27 could be the base for all future patch rebases.  Ubuntu 16.04 and Centos 7 can be cleaned up later, though I suppose it wouldn't hurt anything to leave the old tests there.

**Comment by sm00th** [comment]
Great, the output looks much nicer now :+1:

**Comment by joe-lawrence** [comment]
Nice cleanups.  A few review questions/notes:

- On removing macro-printk.patch:  this means that there no more tests for our ```KPATCH_PRINTK``` macro.  Also, this patch currently fails on F27 (issue #764).
- On removing gcc-static-local-var-5.patch:  this currently fails on F27 (see issue #763).
- I'm on board with removing a bunch of these from the integration tests directory, but it leaves some of the unit test objects files (like bug-table-section, data-read-mostly, etc.) without source patch files.
- `assert_num_funcs()` - would verifying the function names be too much?

**Comment by joe-lawrence** [comment]
> Maybe there's some other way to flush out such random issues.

If we could ever figure out a clean way to import all those historical CVE patches that we worked on, it would offer more than enough input for kpatch to chew on once a release cycle or so.

> And we can continue to brainstorm about how to flush out these kinds of issues, but I don't really like our current method of constantly rebasing the integration tests, as they eventually end up not testing what they were originally intended to test. So I want to keep the integration tests as lean as possible.

I think there are too many and the result is that nobody ends up running them with any regularity.  So trimming them down and splitting off the unit tests moves us to a much better position to do so.

**Pull request merged**
