### PR TITLE
Bump to version v0.9.9

### PR DESCRIPTION
**Pull request by joe-lawrence**
Updates of interest:
v0.9.9:
- Support for gcc-13
- Support for Linux 6.2
- Support for UBSAN kernels
- Fix handling of PowerPC cpu features
- Added RHEL-8.8 and 9.2 integration tests

### CODE REVIEW

**Review by jpoimboe — APPROVED** [review]

**Review by yhcote — APPROVED** [review]
Looks good to me.

**Comment by jpoimboe** [comment]
> Kpatch tools are mature enough and are widely used today. Perhaps, it is time to set version to 1.0 instead of 0.x? @joe-lawrence @jpoimboe, what do you think?

I'm fine with that.  Or we could do 1.0 next time, after the bot closes all the stale bugs.

**Comment by joe-lawrence** [comment]
I was hoping to merge the v0.9.9 tag today, but for v1.0 should we finally remove the deprecated kpatch.ko module?  There's a lot of "experimental" type warnings in the README.md as well that could possibly be toned down.

**Comment by jpoimboe** [comment]
Makes sense.  I can open an issue to track what we want to do for 1.0.

**Comment by euspectre** [comment]
> I was hoping to merge the v0.9.9 tag today, but for v1.0 should we finally remove the deprecated kpatch.ko module? There's a lot of "experimental" type warnings in the README.md as well that could possibly be toned down.

Fine by me. Thanks!

Yes, I agree, it is time for kpatch.ko to go away.

**Pull request merged**
