### PR TITLE
Bump version to v0.9.1

### PR DESCRIPTION
**Pull request by yhcote**
Bump version to v0.9.1

Increment version to v0.9.1 and update v0.9.0's changelog section
following many fixes and improvements.

*Note* that the tree has been tagged to v0.9.0 earlier at
(commit: fd8209aa0052).

### CODE REVIEW

**Comment by yhcote** [comment]
Agreed

**Comment by jpoimboe** [comment]
Doh!

**Comment by jpoimboe** [comment]
I agree this should be changed to v0.9.1.

**Comment by yhcote** [comment]
I updated the commit to create a new v0.9.1 release commit. The commit still holds a log of the changes for v0.9.0.

**Comment by yhcote** [comment]
Should we start using annotation tags?

**Comment by joe-lawrence** [comment]
:+1:

**Comment by joe-lawrence** [comment]
@yhcote : as per last week's kpatch mtg, let's go ahead with the annotated tags.  you should have access to merge/create the release on the github release side, let us know if not.

**Comment by yhcote** [comment]
> @yhcote : as per last week's kpatch mtg, let's go ahead with the annotated tags. you should have access to merge/create the release on the github release side, let us know if not.

Good timing I was working on documenting the steps. Should not be too much longer.

**Pull request merged**
