### PR TITLE
Consider local constants as twins if the sections contain the same data

### PR DESCRIPTION
**Pull request by rudis**
While building a local patch is stumbled over the same (or a similar issue) than #714. The problem seems to be that the section for the local constant (.LC1 in my case) is renamed (similar to gcc's name mangling for functions) and thus not considered as twin section by create-diff-object. The attached patch compares the content of the sections of the twin symbol and marks the section as twin if the content is the same.

Note that I'm not sure if this really is the correct solution as I'm not entirely sure what this local constant is actually used for (it seems related to the kernels __bug_table) and why the section sometimes changes.

### CODE REVIEW

**Comment by jpoimboe** [comment]
Thanks.  The .LC1 symbols are just strings.  GCC assigns all strings a .LCx label, but most of them end up being relocated by their section (e.g., rodata.*.str.1.1) and so they don't end up in the symbol table.  You're right that the bug table is involved here, it refers to them by their .LCx names instead of by their section, so they *do* end up in the symbol table.

I'm not quite sure this is the right approach.  One issue is that the numbering of the .LC symbols might also change.  For example, if a BUG() is inserted towards the beginning of the object file, all the other .LC symbols will be offset by 1.

I'll need to think about it a little more.

**Comment by jpoimboe** [comment]
@rudis do you have a patch which recreates this issue?

**Comment by disaster123** [comment]
@jpoimboe check the patch from my issue: https://github.com/dynup/kpatch/issues/714

**Comment by rudis** [comment]
[test.patch](https://github.com/dynup/kpatch/files/1235719/test.txt)

Yes. The attached patch reproduces it with the current Debian Stretch kernel. To get it either install the packages `linux-image-4.9.0-3-amd64` (for the config), `linux-image-4.9.0-3-amd64-dbg` (for vmlinux) and `linux-source-4.9` (for the source) on a Debian Stretch or download them from `https://packages.debian.org` and unpack them manually. Then unpack the kernel with `tar xf /usr/src/linux-source-4.9.tar.xz` and build it with `kpatch-build -s ./linux-source-4.9 -c /boot/config-4.9.0-3-amd64 -v /usr/lib/debug/vmlinux-4.9.0-3-amd64 test.patch`. This reproduces the issue for me:

```
Using source directory at /home/kpatch/linux-source-4.9
Testing patch file
checking file net/ipv6/ip6_output.c
checking file net/ipv4/ip_output.c
checking file net/ipv4/udp.c
Reading special section data
Building original kernel
Building patched kernel
Extracting new and modified ELF sections
ERROR: ip_output.o: symbol changed sections: .LC0
/usr/lib/kpatch/create-diff-object: unreconcilable difference
udp.o: changed function: udp_send_skb
ERROR: ip6_output.o: symbol changed sections: .LC1
/usr/lib/kpatch/create-diff-object: unreconcilable difference
ERROR: 2 error(s) encountered. Check /home/kpatch/.kpatch/build.log for more details.
```

**Comment by jpoimboe** [comment]
Thanks @rudis , I was able to recreate.  I have a fix coming.

**Comment by disaster123** [comment]
works fine - thanks

**Pull request closed without merging**
