### PR TITLE
[RFC] per-object patches

### PR DESCRIPTION
**Pull request by sm00th**
A stab at making kpatch produce per-object modules instead of a single combined one. Throwing it out there in case someone else is working (or was planning to) on this as well.

### CODE REVIEW

**Comment by joe-lawrence** [comment]
Just curious, what kinds of input patches have you thrown at this?

Might be interesting to see how kpatch-build blows up if you modify some heavily used header file that rebuilds all the modules :)

**Comment by sm00th** [comment]
> Just curious, what kinds of input patches have you thrown at this?

I've been trying out small patches that affect couple of modules + vmlinux. But I do plan to ran through integration tests that will compile on a recent kernel. 

> Might be interesting to see how kpatch-build blows up if you modify some heavily used header file that rebuilds all the modules :)

Thats a great testcase. I tried a meminfo-SLOW patch today and it worked as expected to the point where I hit a CSWITCH issue (and thats why we don't run SLOW patches in integration tests anymore).

The only reason for it to blow up I currently see is a module name collision, which I am not sure can happen.

**Comment by joe-lawrence** [comment]
> The only reason for it to blow up I currently see is a module name collision, which I am not sure can happen.

Was that two similarly named modules from different parts of the source tree?

**Comment by sm00th** [comment]
> > The only reason for it to blow up I currently see is a module name collision, which I am not sure can happen.
> Was that two similarly named modules from different parts of the source tree?

Yes, I've never seen this in a wild but if there are two modules with the exact same name we might have a problem because for now it keeps object files under 'modname.ko/path/to/objfile.o'. I wonder how modprobe handles this or if this is explicitly prohibited somehow.

**Comment by yhcote** [comment]
Work brought into another dev branch.

**Pull request closed without merging**
