### PR TITLE
kpatch-build: add support for static calls

### LINKED ISSUE #1165: kpatch-build: changed section .rela.static_call_sites not selected for inclusion
Yulia noticed that shadow-newpid.patch fails to build on a RHEL-9 kernel (5.12.0-0.rc2.166.el9.x86_64).  Interesting excerpt from the build.log:
```
ERROR: fork.o: 1 unsupported section change(s)
fork.o: WARNING: unable to correlate static local variable ctr.97 used by kernel_clone, assuming variable is new
fork.o: changed function: kernel_clone
fork.o: changed section .rela.static_call_sites not selected for inclusion
create-diff-object: unreconcilable difference
ERROR: exit.o: 1 unsupported section change(s)
exit.o: changed function: do_exit
exit.o: changed section .rela.static_call_sites not selected for inclusion
create-diff-object: unreconcilable difference
array.o: changed function: proc_pid_status
```
[cachedir-tmp-shadow-newpid.tar.gz](https://github.com/dynup/kpatch/files/6172293/cachedir-tmp-shadow-newpid.tar.gz)
[build.log.txt.gz](https://github.com/dynup/kpatch/files/6172304/build.log.txt.gz)

### PR DESCRIPTION
**Pull request by jpoimboe**
Add the new .static_call_sites special section.

Fixes #1165.

Signed-off-by: Josh Poimboeuf <jpoimboe@redhat.com>

### CODE REVIEW

**Comment by jpoimboe** [comment]
v2: fixed script syntax bug in kpatch-build

**Review by kamalesh-babulal — APPROVED** [review]

**Review by joe-lawrence — APPROVED** [review]
Changes LGTM.

Do you want to open another PR to setup unit test cold-noid-issue-1160.env with  STATIC_CALL_STRUCT_SIZE since those object files contain `.static_call_sites`?

**Comment by sm00th** [comment]
> Do you want to open another PR to setup unit test cold-noid-issue-1160.env with STATIC_CALL_STRUCT_SIZE since those object files contain .static_call_sites?

Submodule pointer update with this fix should be a part of this PR.

**Comment by joe-lawrence** [comment]
> Submodule pointer update with this fix should be a part of this PR.

Oh right, somehow I missed that when looking at https://github.com/dynup/kpatch-unit-test-objs/pull/30
So I merged that one, now we just need to bump the submodule for this PR?

**Comment by sm00th** [comment]
Looks like we still need `STATIC_CALL_STRUCT_SIZE` in `cold-noid-issue-1160.env` in unit-test-objs repo.

**Comment by jpoimboe** [comment]
Bumped unit test again, travis is happy now.

**Review by sm00th — APPROVED** [review]

**Pull request merged**
