### PR TITLE
Integration updates

### PR DESCRIPTION
**Pull request by joe-lawrence**
Update the integration tests:

1. Add patches for upstream kernel 5.18.0
2. Fix a warning generated by newer module.patch
3. Add missing syscall test for rhel-9.0 directory

### CODE REVIEW

**Comment by joe-lawrence** [comment]
This PR is mainly to support internal Red Hat integration testing of the s390x arch as will be introduced in #1203 with a few misc cleanups found along the way.

**Comment by jpoimboe** [comment]
I notice rhel-9.0 and linux-5.18.0 also seem to be missing module-call-external.patch?

**Comment by joe-lawrence** [comment]
> I notice rhel-9.0 and linux-5.18.0 also seem to be missing module-call-external.patch?

Deprecated by yours truely in f24f5cb2ca57c6 :)

**Comment by joe-lawrence** [comment]
Merging this now, I'll fix anything outstanding in a follow up PR.

**Pull request merged**
