### PR TITLE
Integration tests rhel-9.5 final

### PR DESCRIPTION
**Pull request by ryanbsull**
Updates integration tests for rhel-9.5 to kernel-5.14.0-503.11.1.el9_5

### CODE REVIEW

**Comment by joe-lawrence** [comment]
Assuming the internal testing passed all arches, can you squash these into a single commit with the last kernel commit msg?  Thanks.

**Comment by ryanbsull** [comment]
@joe-lawrence Beaker hasn't been able to complete a run, just going to spawn a handful of the tasks and hope some push through

**Comment by joe-lawrence** [comment]
Any luck on the tests?  Either way, the commit looks good.

**Comment by ryanbsull** [comment]
@joe-lawrence Sorry forgot to post here, the tests succeeded, put a link on the JIRA ticket, here they are:

https://beaker.engineering.redhat.com/jobs/10102585

**Pull request merged**
