### PR TITLE
Added Table of contents

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
The README was really big at the point that it was hard to navigate, so I decided a Table of contents. Enjoy

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
> Assuming the links are correct, I can't get them to work in the review interface :-)
> 
> Thanks!

I tried the links before sending the merge request, and they all worked.

**Comment by joe-lawrence** [comment]
> Assuming the links are correct, I can't get them to work in the review interface :-)
> 
> Thanks!

For markdown pages, I always go to the code browser to view them.  In this case,
https://github.com/TheEvilSkeleton/kpatch should work.

**Comment by TheEvilSkeleton** [comment]
@joe-lawrence @yhcote @jpoimboe I also added this as a fix for Fedora users: https://github.com/dynup/kpatch/pull/1098/commits/2eeed7bde10601b20af401713e1dfb9abc0b8e00

**Comment by jpoimboe** [comment]
@TheEvilSkeleton kernel-devel isn't the developer kernel, it's the kernel headers and makefiles needed to build kpatch.ko.  Since kpatch.ko is now deprecated, I think we can just remove kernel-devel from the instructions altogether.

**Comment by jpoimboe** [comment]
Looks good to me, thanks.

**Comment by kamalesh-babulal** [comment]
> kernel-devel isn't the developer kernel, it's the kernel headers and makefiles needed to build kpatch.ko. 

Agree, the term developer kernel doesn't represent the kernel-devel correctly.

**Pull request merged**
