### PR TITLE
test/intergation: Rebase to RHEL 8.1

### PR DESCRIPTION
**Pull request by kamalesh-babulal**
Rebase the integration testcase on top of RHEL 8.1 kernel
4.18.0-147.el8.

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by kamalesh-babulal** [comment]
I have currently only tested `data-new.patch` and `new-globals.patch`. I will try to cover more test cases.

**Comment by sm00th** [comment]
Thank you. I'll run them through our ci-thing on 8.1 for both ppc and x86 and will post an update when that finishes.

**Comment by kamalesh-babulal** [comment]
> Thank you. I'll run them through our ci-thing on 8.1 for both ppc and x86 and will post an update when that finishes.

@sm00th Thank you so much for your help.

**Comment by sm00th** [comment]
There is only one failure I am currently seeing: special-static.patch on x86_64
`ERROR: fork.o: kpatch_regenerate_special_section: 2088: Found a jump label at copy_process.part.34()+0x1fc, using key memcg_kmem_enabled_key.  Jump labels aren't currently supported.  Use static_key_enabled() instead.`

**Comment by yhcote** [comment]
> There is only one failure I am currently seeing: special-static.patch on x86_64
> `ERROR: fork.o: kpatch_regenerate_special_section: 2088: Found a jump label at copy_process.part.34()+0x1fc, using key memcg_kmem_enabled_key. Jump labels aren't currently supported. Use static_key_enabled() instead.`

Yep, Got the same here with my RHEL8.3 work-in-progress.

**Comment by joe-lawrence** [comment]
The [kgraft-analysis-tool](https://github.com/marxin/kgraft-analysis-tool) can be helpful in these instances.  For example, we can use it to determine that `copy_signal()` gets inlined into `copy_process()`:
``` shell
% ./kgraft-ipa-analysis.py --symbol=copy_signal <(echo ./usr/src/kernels/4.18.0-161.el8.x86_64-ipaclones/kernel/fork.c.000i.ipa-clones)
Parsing file (1/1): ./usr/src/kernels/4.18.0-161.el8.x86_64-ipaclones/kernel/fork.c.000i.ipa-clones
Function: copy_signal/4917 (kernel/fork.c:1526:12) [REMOVED] [object file: ./usr/src/kernels/4.18.0-161.el8.x86_64-ipaclones/kernel/fork.c.000i.ipa-clones]
  inlining to: copy_process.part.34/5600 (kernel/fork.c:1699:45)

  Affected functions: 1
    copy_process.part.34/5600 (kernel/fork.c:1699:45)
```
That explains why the special-static.patch provokes a kpatch-build complaint for a function that it does not directly modify.

Now to work in the other direction, cscope notes that `memcg_kmem_enabled_key` is referenced by `memcg_kmem_enabled()` and we can construct a called-by call chain from `copy_process` to that reference:

```
copy_process
  dup_task_struct
    memcg_charge_kernel_stack
      memcg_kmem_charge
        memcg_kmem_enabled
          return static_branch_unlikely(&memcg_kmem_enabled_key);
```

And then confirm with the kgraft-analysis-tool that `copy_process` is one of the functions that  `memcg_kmem_enabled` gets inlined into:

``` bash
% ./kgraft-ipa-analysis.py --symbol=memcg_kmem_enabled <(echo ./usr/src/kernels/4.18.0-161.el8.x86_64-ipaclones/kernel/fork.c.000i.ipa-clones)
Parsing file (1/1): ./usr/src/kernels/4.18.0-161.el8.x86_64-ipaclones/kernel/fork.c.000i.ipa-clones
Function: memcg_kmem_enabled/3360 (./include/linux/memcontrol.h:1299:20) [REMOVED] [object file: ./usr/src/kernels/4.18.0-161.el8.x86_64-ipaclones/kernel/fork.c.000i.ipa-clones]
  inlining to: memcg_kmem_uncharge/3362 (./include/linux/memcontrol.h:1311:20) [REMOVED]
    inlining to: free_thread_stack/4364 (kernel/fork.c:255:20) [REMOVED]
      part: free_thread_stack.part.29/5393 (kernel/fork.c:255:20) [REMOVED]
        inlining to: free_thread_stack/4364 (kernel/fork.c:255:20) [REMOVED] [RECURSIVE operation]
        inlining to: put_task_stack/4377 (kernel/fork.c:432:6)
      inlining to: put_task_stack/4377 (kernel/fork.c:432:6)
      inlining to: copy_process.part.34/5600 (kernel/fork.c:1699:45)
  inlining to: memcg_kmem_charge/3361 (./include/linux/memcontrol.h:1304:19) [REMOVED]
    inlining to: memcg_charge_kernel_stack/4375 (kernel/fork.c:388:12) [REMOVED]
      inlining to: dup_task_struct/4406 (kernel/fork.c:837:28) [REMOVED]
        inlining to: copy_process.part.34/5600 (kernel/fork.c:1699:45)

  Affected functions: 8
    memcg_kmem_uncharge/3362 (./include/linux/memcontrol.h:1311:20) [REMOVED]
    free_thread_stack/4364 (kernel/fork.c:255:20) [REMOVED]
    free_thread_stack.part.29/5393 (kernel/fork.c:255:20) [REMOVED]
    put_task_stack/4377 (kernel/fork.c:432:6)
    copy_process.part.34/5600 (kernel/fork.c:1699:45)
    memcg_kmem_charge/3361 (./include/linux/memcontrol.h:1304:19) [REMOVED]
    memcg_charge_kernel_stack/4375 (kernel/fork.c:388:12) [REMOVED]
    dup_task_struct/4406 (kernel/fork.c:837:28) [REMOVED]
```
Unfortunately I don't know how to automate the middle step (connecting the affected function with the original reference), but at least the tool can confirm inlining suspicions.

We might consider disabling the special-static.patch for RHEL-8 for now, but we should determine how to modify the patch to avoid the static key complaint.  I think this will require finding another function that exhibits the same traits @jpoimboe mentioned in https://github.com/dynup/kpatch/issues/402#issuecomment-54890134

**Comment by kamalesh-babulal** [comment]
>There is only one failure I am currently seeing: special-static.patch on x86_64
ERROR: fork.o: kpatch_regenerate_special_section: 2088: Found a jump label at copy_process.part.34()+0x1fc, using key memcg_kmem_enabled_key. Jump labels aren't currently supported. Use static_key_enabled() instead.

triggers on powerpc too.

**Comment by joe-lawrence** [comment]
@kamalesh-babulal :  small spelling nit:  s/intergation/integration/g on the two commit messages.  If special-static.patch was the only failing test, then this would be ready to merge after this change, ya?

**Comment by kamalesh-babulal** [comment]
>  small spelling nit: s/intergation/integration/g on the two commit messages. If special-static.patch was the only failing test, then this would be ready to merge after this change, ya?

@joe-lawrence Thanks for the review and analyzing the failure. @sm00th Thanks for the test runs.

**Pull request merged**
