### PR TITLE
Bump to version v0.9.8

### PR DESCRIPTION
**Pull request by joe-lawrence**
Updates of interest:
v0.9.8:
- Clang fix ups from Pete Swain
- Support for gcc-12
- Support for Linux 5.19
- Added RHEL-8.7 and 9.1 integration tests
- Fixed __UNIQUE_ID() variable correlation
- Improved handling of unsupported static calls

### CODE REVIEW

**Comment by joe-lawrence** [comment]
Thanks to Yulia Kopkova for running the integration tests for the following release/arch combinations (all pass):

- Fedora-36 Server x86_64, s390x, ppc64le
- RHEL-9.0.0 BaseOS x86_64, ppc64le
- RHEL-8.6.0 BaseOS x86_64, ppc64le
- RHEL-8.4.0 BaseOS x86_64, ppc64le
- RHEL-8.2.0 BaseOS x86_64, ppc64le
- RHEL-8.1.0 BaseOS x86_64, ppc64le
- RHEL-7.9 Server x86_64, ppc64le
- RHEL-7.7 Server x86_64, ppc64le

**Comment by liu-song-6** [comment]
Thanks!!

**Review by yhcote — APPROVED** [review]
Looks good to me

**Comment by jpoimboe** [comment]
> Thanks to Yulia Kopkova for running the integration tests for the following release/arch combinations (all pass):
> 
>     * Fedora-36 Server x86_64, s390x, ppc64le
> 
>     * RHEL-9.0.0 BaseOS x86_64, ppc64le
> 
>     * RHEL-8.6.0 BaseOS x86_64, ppc64le
> 
>     * RHEL-8.4.0 BaseOS x86_64, ppc64le
> 
>     * RHEL-8.2.0 BaseOS x86_64, ppc64le
> 
>     * RHEL-8.1.0 BaseOS x86_64, ppc64le
> 
>     * RHEL-7.9 Server x86_64, ppc64le
> 
>     * RHEL-7.7 Server x86_64, ppc64le

I thought the integration tests were automatically running for pull requests, or did something change?

**Comment by joe-lawrence** [comment]
> > Thanks to Yulia Kopkova for running the integration tests for the following release/arch combinations (all pass):
> > ```
> > * Fedora-36 Server x86_64, s390x, ppc64le
> > 
> > * RHEL-9.0.0 BaseOS x86_64, ppc64le
> > 
> > * RHEL-8.6.0 BaseOS x86_64, ppc64le
> > 
> > * RHEL-8.4.0 BaseOS x86_64, ppc64le
> > 
> > * RHEL-8.2.0 BaseOS x86_64, ppc64le
> > 
> > * RHEL-8.1.0 BaseOS x86_64, ppc64le
> > 
> > * RHEL-7.9 Server x86_64, ppc64le
> > 
> > * RHEL-7.7 Server x86_64, ppc64le
> > ```
> 
> I thought the integration tests were automatically running for pull requests, or did something change?

From her email, "Integration tests were failing due to dwarves-1.24 package getting installed from Fedora updates and it caused an issue when building with 5.18."  This would apply to the first few Fedora-36 tests (fedora + upstream kernel).

**Review by jpoimboe — APPROVED** [review]

**Pull request merged**
