### PR TITLE
deal with the deadlock may occur in stop_machine context.

### PR DESCRIPTION
**Pull request by zhenjiangma**
we remove the pre_patch_callback/post_unpatch_callback from the
stop_machine context. If a schedule/sleep happend in callbacks while the
process to be scheuded later will send IPI, because all interrupts
are disabled, the machine will trap into a  deadlock in such situation.
So we remove the pre_patch_callback and post_unpatch_callback from
the stop_machine to avoid such situation. On the other hand, to avoid
the race between the patched code and post-patch/pre-unpatch callbacks when
run in parallel, we didn't remove  the post_patch_callback and
pre_unpatch_callback from stop_machine.

### CODE REVIEW

**Comment by zhenjiangma** [comment]
We have made modifications accoding to the suggestions based on the previous ones #1126.

**Comment by euspectre** [comment]
I have tested the patch on my system - seems to work OK. I cannot see any major problems with the patch.

Please fix the minor issues I pointed out above and, I think, the patch will be acceptable after that.

**Comment by euspectre** [comment]
Besides, you can close https://github.com/dynup/kpatch/pull/1126, I think, as the discussion has moved here.

You can remove the previous version of the fix from https://github.com/zhenjiangma/kpatch:master (using 'git rebase -i HEAD^', for example) and force-push the new fix there. This way, this pull request #1134 will be reused.

**Comment by zhenjiangma** [comment]
> Besides, you can close #1126, I think, as the discussion has moved here.
> 
> You can remove the previous version of the fix from https://github.com/zhenjiangma/kpatch:master (using 'git rebase -i HEAD^', for example) and force-push the new fix there. This way, this pull request #1134 will be reused.

Thanks for your suggestions, I've fixed the minor issues according to your suggestions. 
I‘ve tried my best to learn 'git rebase -i HEAD^' to reuse the pull request #1134, but it didn't seem to work. And finally, I made a new commit b311112 base on last commit using 'git commit --amend' to reuse this request.

**Review by euspectre — APPROVED** [review]
Sorry for the delay.

The patch looks good to me now. The tests haven't shown any problems yet.

**Comment by zhenjiangma** [comment]
> Sorry for the delay.
> 
> The patch looks good to me now. The tests haven't shown any problems yet.

You are welcome, I'm very glad that I can contribute to the community.

**Comment by joe-lawrence** [comment]
Thanks @zhenjiangma and @euspectre, the changes look reasonable and thank you for testing.

**Pull request merged**
