### PR TITLE
Remove .klp.arch and add jump label support

### PR DESCRIPTION
**Pull request by jpoimboe**
This is the companion pull request for my upstream posting to remove .klp.arch and add support for jump labels.

https://lkml.kernel.org/r/cover.1586881704.git.jpoimboe@redhat.com

### CODE REVIEW

**Comment by sm00th** [comment]
That was a fast merge.

Should we close #940 now and deal with the tests disabled by it?

**Comment by yhcote** [comment]
Hmm, I understood that the 1st merge of that PR introduced failures. So I merged the commit updating to the submodule. Let me know if I misread the situation.

**Comment by sm00th** [comment]
> 1st merge of that PR introduced failures

There was no first merge. Integration tests ran on PR creation and sent a warning about issues with the PR.

**Comment by yhcote** [comment]
Ah dear github...  A merged PR was mention to the thread which just looks like the sequence of commit was merged. And the conversation around the CI at that moment really got me. Sorry everyone for that.

**Comment by jpoimboe** [comment]
Oh well, not a big deal :-)  Review comments are still very welcome, I can a submit followup PR if needed.

**Pull request merged**
