### PR TITLE
test/integration: add RHEL-8.2 integration tests

### PR DESCRIPTION
**Pull request by joe-lawrence**
For kernel-4.18.0-193.el8.

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>

### CODE REVIEW

**Comment by jpoimboe** [comment]
Compared to the RHEL 8.1 tests, gcc-static-local-var-5.patch and shadow-newpid-LOADED.test are disabled.  It would be good to have the justification for those changes in the commit log.

**Comment by joe-lawrence** [comment]
gcc-static-local-var-5.patch: I'll fetch that that info tomorrow
shadow-newpid-LOADED.test: in RHEL-8.1, it's shadow-newpid.patch.disabled so I disabled the the test to match

**Comment by sm00th** [comment]
> shadow-newpid-LOADED.test: in RHEL-8.1, it's shadow-newpid.patch.disabled so I disabled the the test to match

Could you also please disable the test on 8.1 in a separate commit (but same pr)? It is not required (looking at the code it just detects that corresponding module is not there and just complains and skips the test) but won't hurt to be consistent.

**Comment by joe-lawrence** [comment]
> Compared to the RHEL 8.1 tests, gcc-static-local-var-5.patch and shadow-newpid-LOADED.test are disabled. It would be good to have the justification for those changes in the commit log.

I enabled all the tests and re-ran them on the latest 8.2 z-stream build, disabled those that no longer built and noted them in the commit message.

**Pull request merged**
