### PR TITLE
Add new r_info field to kpatch_patch_dynrela and rela structs

### PR DESCRIPTION
**Pull request by flaming-toast**
Save the `r_info` field in create-diff-object to pass into `klp_write_module_reloc()`.

### CODE REVIEW

**Comment by jpoimboe** [comment]
Thanks!  Looks good to me.

Need to keep this PR on hold for now, because it depends on a future upstream `struct klp_reloc` change.

**Comment by flaming-toast** [comment]
Sounds good, upstream patch soon to follow :-)

**Comment by spartacus06** [comment]
I haven't been following the discussion closely, but it seems to me that all of the data contained in r_info is already store, in a form, in the fields we have.  r_info contains the type, which is has a fields, and the symbol index, which is indirectly stored in the associated symbol.  The symbols are reindexed by create-diff-object, so the original symbol index doesn't matter.

**Comment by flaming-toast** [comment]
@spartacus06 Thanks for the feedback! We eventually need to use the symbol index in `klp_write_module_reloc` (for s390x), as PLT and GOT offsets (used in certain s390 relocation types) are accessed via module->arch.syminfo + symbol index. I didn't see a way to access symbol index information once we're already in `klp_write_object_relocations()`, since we don't save this information in the `klp_reloc` structs. I decided saving `r_info` might be useful since we can then extract both the relocation type and sym index from it. Do you happen see another way to access symbol indices?

**Comment by jpoimboe** [comment]
Since type is encoded in `r_info`, I guess we can remove `type` from `klp_reloc`?

@spartacus06, good point about the original symbol index being irrelevant.  The new index is generated in `kpatch_reindex_elements()` and encoded into the new `r_info` in `kpatch_rebuild_rela_section_data()`.

**Comment by flaming-toast** [comment]
Hmmm... Actually now considering the reindexing, I think the old `r_info`'s are being saved in the `.kpatch.dynrelas` section in `kpatch_create_dynamic_rela_sections()` instead of the new ones generated in `kpatch_rebuild_rela_section_data()`, since the former is called before the latter. Pretty sure we want to save the new one :-) I'll have to rethink this more..

**Comment by spartacus06** [comment]
Wow, my English was horrible in my comment.  It's like I've been doing the same 4 demos for 6 hours at a conference and extremely sleep deprived or something :P

**Comment by jpoimboe** [comment]
I think we decided that a different approach is needed.  Closing...

**Pull request closed without merging**
