### PR TITLE
test/integration: rhel-8.1 Add missing *.test files

### PR DESCRIPTION
**Pull request by kamalesh-babulal**
Add the missing *.test files in test/integration/rhel-8.1

Signed-off-by: Kamalesh Babulal <kamalesh@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by kamalesh-babulal** [comment]
> One thing: gcc-static-local-var-4.test needs to be disabled because it's parent module is disabled. Renaming it to gcc-static-local-var-4.test.disabled should work I think.

@sm00th Thanks for the review. Pushed the updated patch.

**v2 Changes:**
- Disabled the `gcc-static-local-var-4.test`

**Comment by yhcote** [comment]
@sm00th, @kamalesh-babulal: Has it run through the CI or a local run for verification?

**Comment by kamalesh-babulal** [comment]
@yhcote previous PR to add the test cases went through the CI runs by Artem and some of the tests were locally build by me, not this PR. @sm00th Thanks again for the review and the runs.

**Comment by yhcote** [comment]
> @yhcote previous PR to add the test cases went through the CI runs by Artem and some of the tests were locally build by me, not this PR. @sm00th Thanks again for the review and the runs.

Thanks! @sm00th, @kamalesh-babulal

**Pull request merged**
