### PR TITLE
Fix static code analyzer complaints

### PR DESCRIPTION
**Pull request by joe-lawrence**
These are mostly trivial, but really simple to clean up.  With a clean slate, we can monitor future pull requests that may introduce new complaints  (I have a script in the works).

### CODE REVIEW

**Comment by jpoimboe** [comment]
@joe-lawrence nice!  BTW, I'm surprised it didn't complain about all the non-static functions in create-diff-object.c.

:+1:

**Comment by jpoimboe** [comment]
Also surprised it didn't find more bugs!

**Comment by joe-lawrence** [comment]
Ahh, I was only running the checks on the driver directories...  Let me look into checking the entire project.

**Comment by flaming-toast** [comment]
I'll go ahead and merge this now since it has a 👍 :-) If you find more smatch/sparse complaints, feel free to open another pull request.

**Pull request merged**
