### PR TITLE
Added Supported Architectures category

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
- Added Supported Architectures category to avoid confusion (for example https://github.com/dynup/kpatch/issues/1099#issuecomment-625913876).
- Updated Prerequisites category

### CODE REVIEW

**Comment by jpoimboe** [comment]
How about calling the section "Supported Architectures" and moving it before Installation (like the TOC shows)?

I would do the checklist something like:

- [x] x86-64
- [x] ppc64le
- [ ] arm64
- [ ] s390

Because I haven't heard of any plans to support other architectures beyond those four.

Also please squash the commits into a single commit with an appropriate subject and description.  

Thanks.

**Comment by TheEvilSkeleton** [comment]
> How about calling the section "Supported Architectures" and moving it before Installation (like the TOC shows)?

Oops. User error

**Comment by TheEvilSkeleton** [comment]
@jpoimboe Not really sure how I can squash commits.

I have found online that a member of the repository can squash commits https://github.blog/2016-04-01-squash-your-commits/

**Comment by jpoimboe** [comment]
You can 'git rebase -i' to squash them locally and then 'git push --force' to your branch.

**Comment by TheEvilSkeleton** [comment]
Seems good to me now

**Pull request merged**
